### ISSUE TITLE
Security Data : UsernameToken authentication failed

### ISSUE THREAD

**Issue by MikeOshadami** [e-payment/cybersource-soap-java#1]
When I run the mvn test, I get the error below;

AxisFault
 faultCode: {http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd}FailedCheck
 faultSubcode: 
 faultString: 
Security Data : UsernameToken authentication failed.

 faultActor: 
 faultNode: 
 faultDetail: 
	{http://xml.apache.org/axis/}stackTrace:
Security Data : UsernameToken authentication failed.

**Comment by junlapong** [comment]
You need to set your merchant Id and transaction key in the cybs.properties
Are you have an cybersource evaluation account?

**Comment by oshadami** [comment]
I have done that, the issue is that the soap header does not contain the security username and password.
